# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Prolific' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Prolific
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'lottie-ios', '2.5.3'
  pod 'IQKeyboardManager'

  target 'ProlificTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProlificUITests' do
    # Pods for testing
  end

end
